services:
  user-app:
    image: mmpotulo28/taxyciti-user:latest
    container_name: taxyciti-user
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production
    networks:
      - taxyciti-net

  driver-app:
    image: mmpotulo28/taxyciti-driver:latest
    container_name: taxyciti-driver
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - .env.production
    networks:
      - taxyciti-net

  websocket-server:
    image: mmpotulo28/taxyciti-websocket:latest
    container_name: taxyciti-websocket
    restart: always
    ports:
      - "127.0.0.1:3006:3006"
    env_file:
      - .env.production
      - .env.local
    networks:
      - taxyciti-net

networks:
  taxyciti-net:
    driver: bridge
