services:
  user-app:
    image: mmpotulo28/taxiciti-user:latest
    container_name: taxiciti-user
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production
    networks:
      - taxiciti-net

  driver-app:
    image: mmpotulo28/taxiciti-driver:latest
    container_name: taxiciti-driver
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - .env.production
    networks:
      - taxiciti-net

  websocket-server:
    image: mmpotulo28/taxiciti-websocket:latest
    container_name: taxiciti-websocket
    restart: always
    ports:
      - "127.0.0.1:3006:3006"
    env_file:
      - .env.production
    networks:
      - taxiciti-net

networks:
  taxiciti-net:
    driver: bridge
