packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - vue-demi

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  diff@<8.0.3: '>=8.0.3'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  tar@<=7.5.2: '>=7.5.3'
  undici@<6.23.0: '>=6.23.0'
