import { iRank, iRoute, iTaxi, iTrip } from "../types";

// Mock Ranks Data
export const ranks: iRank[] = [
	{
		id: "rank1",
		name: "Johannesburg CBD Rank",
		coordinates: {
			lat: -26.2041,
			lng: 28.0473,
		},
		address: "Bree Street, Johannesburg CBD",
		phone: "011 555 1234",
		region: "Gauteng",
	},
	{
		id: "rank2",
		name: "Sandton Rank",
		coordinates: {
			lat: -26.1052,
			lng: 28.0568,
		},
		address: "Rivonia Road, Sandton",
		phone: "011 555 5678",
		region: "Gauteng",
	},
	{
		id: "rank3",
		name: "Pretoria Central Rank",
		coordinates: {
			lat: -25.7479,
			lng: 28.2293,
		},
		address: "Bosman Street, Pretoria Central",
		phone: "012 555 9012",
		region: "Gauteng",
	},
	{
		id: "rank4",
		name: "Soweto Rank",
		coordinates: {
			lat: -26.2686,
			lng: 27.8582,
		},
		address: "Old Potchefstroom Road, Soweto",
		phone: "011 555 3456",
		region: "Gauteng",
	},
	{
		id: "rank5",
		name: "Durban Central Rank",
		coordinates: {
			lat: -29.8587,
			lng: 31.0218,
		},
		address: "Warwick Avenue, Durban Central",
		phone: "031 555 7890",
		region: "KwaZulu-Natal",
	},
];

// Mock Routes Data
export const routes: iRoute[] = [
	{
		id: "route1",
		name: "Johannesburg CBD to Sandton",
		rankId: "rank1",
		destinationRankId: "rank2",
		estimatedDuration: "30-40 min",
		estimatedFare: "R25.00",
		distance: "14.7 km",
		status: "active",
	},
	{
		id: "route2",
		name: "Johannesburg CBD to Pretoria",
		rankId: "rank1",
		destinationRankId: "rank3",
		estimatedDuration: "45-60 min",
		estimatedFare: "R65.00",
		distance: "57.8 km",
		status: "active",
	},
	{
		id: "route3",
		name: "Johannesburg CBD to Soweto",
		rankId: "rank1",
		destinationRankId: "rank4",
		estimatedDuration: "35-45 min",
		estimatedFare: "R20.00",
		distance: "23.5 km",
		status: "active",
	},
	{
		id: "route4",
		name: "Sandton to Pretoria",
		rankId: "rank2",
		destinationRankId: "rank3",
		estimatedDuration: "40-50 min",
		estimatedFare: "R45.00",
		distance: "42.1 km",
		status: "busy",
	},
	{
		id: "route5",
		name: "Pretoria to Johannesburg",
		rankId: "rank3",
		destinationRankId: "rank1",
		estimatedDuration: "45-60 min",
		estimatedFare: "R65.00",
		distance: "57.8 km",
		status: "active",
	},
];

// Mock Taxis Data
export const taxis: iTaxi[] = [
	{
		id: "taxi1",
		driver: "Sipho Nkosi",
		model: "Toyota Quantum",
		licensePlate: "GP 123-456",
		capacity: 15,
		rating: 4.8,
		status: "available",
		location: {
			lat: -26.2051,
			lng: 28.0483,
		},
		eta: "5 min",
		routeId: "route1",
		phone: "073 123 4567",
	},
	{
		id: "taxi2",
		driver: "Thabo Molefe",
		model: "Toyota Hiace",
		licensePlate: "GP 789-012",
		capacity: 15,
		rating: 4.5,
		status: "available",
		location: {
			lat: -26.2031,
			lng: 28.0453,
		},
		eta: "3 min",
		routeId: "route1",
		phone: "082 345 6789",
	},
	{
		id: "taxi3",
		driver: "Mandla Zulu",
		model: "Nissan Impendulo",
		licensePlate: "GP 345-678",
		capacity: 16,
		rating: 4.7,
		status: "busy",
		location: {
			lat: -26.1062,
			lng: 28.0578,
		},
		routeId: "route2",
		phone: "076 567 8901",
	},
	{
		id: "taxi4",
		driver: "Themba Ndlovu",
		model: "Toyota Quantum",
		licensePlate: "GP 901-234",
		capacity: 15,
		rating: 4.9,
		status: "available",
		location: {
			lat: -26.2696,
			lng: 27.8592,
		},
		eta: "7 min",
		routeId: "route3",
		phone: "071 890 1234",
	},
	{
		id: "taxi5",
		driver: "David Mkhize",
		model: "Mercedes-Benz Sprinter",
		licensePlate: "GP 567-890",
		capacity: 22,
		rating: 4.6,
		status: "offline",
		routeId: "route4",
		phone: "084 012 3456",
	},
];

// Mock Trip History Data
export const trips: iTrip[] = [
	{
		id: "trip1",
		route: "Johannesburg CBD to Sandton",
		date: "2023-11-15",
		time: "08:30 AM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Rivonia Road, Sandton",
		driver: "Sipho Nkosi",
		vehicle: "Toyota Quantum",
		licensePlate: "GP 123-456",
		fare: "R25.00",
		status: "completed",
		paymentMethod: "Cash",
		rating: 5,
	},
	{
		id: "trip2",
		route: "Sandton to Pretoria",
		date: "2023-11-10",
		time: "14:15 PM",
		pickup: "Rivonia Road, Sandton",
		dropoff: "Bosman Street, Pretoria Central",
		driver: "Thabo Molefe",
		vehicle: "Toyota Hiace",
		licensePlate: "GP 789-012",
		fare: "R45.00",
		status: "completed",
		paymentMethod: "QR Code",
		rating: 4,
	},
	{
		id: "trip3",
		route: "Johannesburg CBD to Soweto",
		date: "2023-11-05",
		time: "17:45 PM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Old Potchefstroom Road, Soweto",
		driver: "Mandla Zulu",
		vehicle: "Nissan Impendulo",
		licensePlate: "GP 345-678",
		fare: "R20.00",
		status: "completed",
		paymentMethod: "Cash",
	},
	{
		id: "trip4",
		route: "Pretoria to Johannesburg",
		date: "2023-10-28",
		time: "09:00 AM",
		pickup: "Bosman Street, Pretoria Central",
		dropoff: "Bree Street, Johannesburg CBD",
		driver: "Themba Ndlovu",
		vehicle: "Toyota Quantum",
		licensePlate: "GP 901-234",
		fare: "R65.00",
		status: "cancelled",
		paymentMethod: "N/A",
	},
	{
		id: "trip5",
		route: "Johannesburg CBD to Sandton",
		date: "2023-10-20",
		time: "16:30 PM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Rivonia Road, Sandton",
		driver: "David Mkhize",
		vehicle: "Mercedes-Benz Sprinter",
		licensePlate: "GP 567-890",
		fare: "R25.00",
		status: "completed",
		paymentMethod: "QR Code",
		rating: 5,
	},
];
