import { iRank, iRoute, iTrip, iTaxi } from "@/types";

// Sample Ranks Data
export const ranks: iRank[] = [
	{
		id: "rank1",
		name: "Bree Street Taxi Rank",
		location: "Johannesburg CBD",
		coordinates: { lat: -26.2044, lng: 28.0456 },
		capacity: 120,
		operatingHours: "04:00 - 21:00",
	},
	{
		id: "rank2",
		name: "Cape Town Station Deck",
		location: "Cape Town CBD",
		coordinates: { lat: -33.9241, lng: 18.4231 },
		capacity: 200,
		operatingHours: "04:30 - 22:00",
	},
	{
		id: "rank3",
		name: "Durban Station",
		location: "Durban CBD",
		coordinates: { lat: -29.855, lng: 31.028 },
		capacity: 150,
		operatingHours: "04:00 - 21:30",
	},
	{
		id: "rank4",
		name: "Noord Street Taxi Rank",
		location: "Johannesburg",
		coordinates: { lat: -26.1975, lng: 28.0421 },
		capacity: 180,
		operatingHours: "04:00 - 20:00",
	},
	{
		id: "rank5",
		name: "Pretoria Station",
		location: "Pretoria CBD",
		coordinates: { lat: -25.7542, lng: 28.188 },
		capacity: 130,
		operatingHours: "04:30 - 21:00",
	},
];

// Sample Routes Data
export const routes: iRoute[] = [
	{
		id: "route1",
		name: "Johannesburg CBD to Soweto",
		rankId: "rank1",
		description: "Direct route from Bree Street to Soweto via Main Reef Road",
		estimatedFare: "R25 - R30",
		estimatedDuration: "45 min",
		distance: "23 km",
		status: "active",
	},
	{
		id: "route2",
		name: "Cape Town to Bellville",
		rankId: "rank2",
		description: "Route connecting Cape Town CBD to Bellville",
		estimatedFare: "R20 - R25",
		estimatedDuration: "35 min",
		distance: "20 km",
		status: "busy",
	},
	{
		id: "route3",
		name: "Durban CBD to Umlazi",
		rankId: "rank3",
		description: "Regular route from Durban Station to Umlazi Township",
		estimatedFare: "R18 - R22",
		estimatedDuration: "30 min",
		distance: "17 km",
		status: "active",
	},
	{
		id: "route4",
		name: "Johannesburg to Sandton",
		rankId: "rank4",
		description: "Busy route connecting Johannesburg CBD to Sandton",
		estimatedFare: "R22 - R28",
		estimatedDuration: "40 min",
		distance: "15 km",
		status: "active",
	},
	{
		id: "route5",
		name: "Pretoria to Centurion",
		rankId: "rank5",
		description: "Regular route from Pretoria Station to Centurion",
		estimatedFare: "R20 - R25",
		estimatedDuration: "25 min",
		distance: "14 km",
		status: "delayed",
	},
	{
		id: "route6",
		name: "Johannesburg to Pretoria",
		rankId: "rank1",
		description: "Long distance route connecting Johannesburg to Pretoria",
		estimatedFare: "R70 - R80",
		estimatedDuration: "1 hr 20 min",
		distance: "58 km",
		status: "active",
	},
	{
		id: "route7",
		name: "Cape Town to Stellenbosch",
		rankId: "rank2",
		description: "Route from Cape Town to Stellenbosch",
		estimatedFare: "R35 - R45",
		estimatedDuration: "50 min",
		distance: "40 km",
		status: "active",
	},
	{
		id: "route8",
		name: "Durban to Pinetown",
		rankId: "rank3",
		description: "Regular service from Durban CBD to Pinetown",
		estimatedFare: "R18 - R22",
		estimatedDuration: "30 min",
		distance: "19 km",
		status: "busy",
	},
];

// Sample Trip History Data
export const trips: iTrip[] = [
	{
		id: "trip1",
		route: "Johannesburg CBD to Soweto",
		date: "2023-10-15",
		time: "08:30 AM",
		pickup: "Bree Street Taxi Rank",
		dropoff: "Orlando Stadium, Soweto",
		fare: "R28",
		status: "completed",
		driver: "Thabo Molefe",
		vehicle: "Toyota Quantum (White)",
		licensePlate: "GP ABC 123",
		paymentMethod: "Cash",
	},
	{
		id: "trip2",
		route: "Cape Town to Bellville",
		date: "2023-10-12",
		time: "10:15 AM",
		pickup: "Cape Town Station Deck",
		dropoff: "Bellville Taxi Rank",
		fare: "R22",
		status: "completed",
		driver: "Michael Adonis",
		vehicle: "Toyota HiAce (Silver)",
		licensePlate: "CA XYZ 789",
		paymentMethod: "Cash",
	},
	{
		id: "trip3",
		route: "Johannesburg to Sandton",
		date: "2023-10-08",
		time: "09:00 AM",
		pickup: "Noord Street Taxi Rank",
		dropoff: "Sandton City",
		fare: "R25",
		status: "completed",
		driver: "Samuel Ndlovu",
		vehicle: "Toyota Quantum (Silver)",
		licensePlate: "GP DEF 456",
		paymentMethod: "Cash",
	},
	{
		id: "trip4",
		route: "Pretoria to Centurion",
		date: "2023-09-30",
		time: "07:45 AM",
		pickup: "Pretoria Station",
		dropoff: "Centurion Mall",
		fare: "R22",
		status: "completed",
		driver: "David van Wyk",
		vehicle: "Nissan Impendulo (White)",
		licensePlate: "GP GHI 789",
		paymentMethod: "Cash",
	},
	{
		id: "trip5",
		route: "Johannesburg to Pretoria",
		date: "2023-09-25",
		time: "06:30 AM",
		pickup: "Bree Street Taxi Rank",
		dropoff: "Pretoria CBD",
		fare: "R75",
		status: "cancelled",
		driver: "Jacob Zuma",
		vehicle: "Mercedes Sprinter (White)",
		licensePlate: "GP JKL 012",
		paymentMethod: "Not applicable",
	},
];

// Sample Taxis Data
export const taxis: iTaxi[] = [
	{
		id: "taxi1",
		registrationNumber: "GP ABC 123",
		driver: "Thabo Molefe",
		phone: "072 123 4567",
		capacity: 15,
		model: "Toyota Quantum (White)",
		status: "available",
		routes: ["route1", "route6"],
		rating: 4.7,
		location: { lat: -26.205, lng: 28.045 },
	},
	{
		id: "taxi2",
		registrationNumber: "CA XYZ 789",
		driver: "Michael Adonis",
		phone: "083 987 6543",
		capacity: 15,
		model: "Toyota HiAce (Silver)",
		status: "on-trip",
		routes: ["route2", "route7"],
		rating: 4.5,
		location: { lat: -33.923, lng: 18.424 },
	},
	{
		id: "taxi3",
		registrationNumber: "GP DEF 456",
		driver: "Samuel Ndlovu",
		phone: "076 555 7777",
		capacity: 16,
		model: "Toyota Quantum (Silver)",
		status: "available",
		routes: ["route4", "route6"],
		rating: 4.8,
		location: { lat: -26.198, lng: 28.043 },
	},
	{
		id: "taxi4",
		registrationNumber: "GP GHI 789",
		driver: "David van Wyk",
		phone: "082 444 3333",
		capacity: 15,
		model: "Nissan Impendulo (White)",
		status: "offline",
		routes: ["route5"],
		rating: 4.2,
		location: { lat: -25.754, lng: 28.189 },
	},
	{
		id: "taxi5",
		registrationNumber: "NPN JKL 012",
		driver: "Sibusiso Cele",
		phone: "071 222 8888",
		capacity: 16,
		model: "Toyota Quantum (White)",
		status: "available",
		routes: ["route3", "route8"],
		rating: 4.6,
		location: { lat: -29.856, lng: 31.029 },
	},
];
