import { iRank, iRoute, iTaxi, iTrip, iAdminUser } from "@/types";

// Mock Ranks Data
export const ranks: iRank[] = [
	{
		id: "rank1",
		name: "Johannesburg CBD Rank",
		coordinates: {
			lat: -26.2041,
			lng: 28.0473,
		},
		address: "Bree Street, Johannesburg CBD",
		phone: "011 555 1234",
		region: "Gauteng",
	},
	{
		id: "rank2",
		name: "Sandton Rank",
		coordinates: {
			lat: -26.1052,
			lng: 28.0568,
		},
		address: "Rivonia Road, Sandton",
		phone: "011 555 5678",
		region: "Gauteng",
	},
	{
		id: "rank3",
		name: "Pretoria Central Rank",
		coordinates: {
			lat: -25.7479,
			lng: 28.2293,
		},
		address: "Bosman Street, Pretoria Central",
		phone: "012 555 9012",
		region: "Gauteng",
	},
	{
		id: "rank4",
		name: "Soweto Rank",
		coordinates: {
			lat: -26.2686,
			lng: 27.8582,
		},
		address: "Old Potchefstroom Road, Soweto",
		phone: "011 555 3456",
		region: "Gauteng",
	},
	{
		id: "rank5",
		name: "Durban Central Rank",
		coordinates: {
			lat: -29.8587,
			lng: 31.0218,
		},
		address: "Warwick Avenue, Durban Central",
		phone: "031 555 7890",
		region: "KwaZulu-Natal",
	},
];

// Mock Routes Data
export const routes: iRoute[] = [
	{
		id: "route1",
		name: "Johannesburg CBD to Sandton",
		rankId: "rank1",
		destinationRankId: "rank2",
		estimatedDuration: "30-40 min",
		estimatedFare: "R25.00",
		distance: "14.7 km",
		status: "active",
	},
	{
		id: "route2",
		name: "Johannesburg CBD to Pretoria",
		rankId: "rank1",
		destinationRankId: "rank3",
		estimatedDuration: "45-60 min",
		estimatedFare: "R65.00",
		distance: "57.8 km",
		status: "active",
	},
	{
		id: "route3",
		name: "Johannesburg CBD to Soweto",
		rankId: "rank1",
		destinationRankId: "rank4",
		estimatedDuration: "35-45 min",
		estimatedFare: "R20.00",
		distance: "23.5 km",
		status: "active",
	},
	{
		id: "route4",
		name: "Sandton to Pretoria",
		rankId: "rank2",
		destinationRankId: "rank3",
		estimatedDuration: "40-50 min",
		estimatedFare: "R45.00",
		distance: "42.1 km",
		status: "busy",
	},
	{
		id: "route5",
		name: "Pretoria to Johannesburg",
		rankId: "rank3",
		destinationRankId: "rank1",
		estimatedDuration: "45-60 min",
		estimatedFare: "R65.00",
		distance: "57.8 km",
		status: "active",
	},
];

// Mock Taxis Data
export const taxis: iTaxi[] = [
	{
		id: "taxi1",
		driver: "Sipho Nkosi",
		model: "Toyota Quantum",
		licensePlate: "GP 123-456",
		capacity: 15,
		rating: 4.8,
		status: "available",
		location: {
			lat: -26.2051,
			lng: 28.0483,
		},
		eta: "5 min",
		routeId: "route1",
		phone: "073 123 4567",
	},
	{
		id: "taxi2",
		driver: "Thabo Molefe",
		model: "Toyota Hiace",
		licensePlate: "GP 789-012",
		capacity: 15,
		rating: 4.5,
		status: "available",
		location: {
			lat: -26.2031,
			lng: 28.0453,
		},
		eta: "3 min",
		routeId: "route1",
		phone: "082 345 6789",
	},
	{
		id: "taxi3",
		driver: "Mandla Zulu",
		model: "Nissan Impendulo",
		licensePlate: "GP 345-678",
		capacity: 16,
		rating: 4.7,
		status: "busy",
		location: {
			lat: -26.1062,
			lng: 28.0578,
		},
		routeId: "route2",
		phone: "076 567 8901",
	},
	{
		id: "taxi4",
		driver: "Themba Ndlovu",
		model: "Toyota Quantum",
		licensePlate: "GP 901-234",
		capacity: 15,
		rating: 4.9,
		status: "available",
		location: {
			lat: -26.2696,
			lng: 27.8592,
		},
		eta: "7 min",
		routeId: "route3",
		phone: "071 890 1234",
	},
	{
		id: "taxi5",
		driver: "David Mkhize",
		model: "Mercedes-Benz Sprinter",
		licensePlate: "GP 567-890",
		capacity: 22,
		rating: 4.6,
		status: "offline",
		routeId: "route4",
		phone: "084 012 3456",
	},
];

// Mock Trip History Data
export const trips: iTrip[] = [
	{
		id: "trip1",
		route: "Johannesburg CBD to Sandton",
		date: "2023-11-15",
		time: "08:30 AM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Rivonia Road, Sandton",
		driver: "Sipho Nkosi",
		vehicle: "Toyota Quantum",
		licensePlate: "GP 123-456",
		fare: "R25.00",
		status: "completed",
		paymentMethod: "Cash",
		rating: 5,
	},
	{
		id: "trip2",
		route: "Sandton to Pretoria",
		date: "2023-11-10",
		time: "14:15 PM",
		pickup: "Rivonia Road, Sandton",
		dropoff: "Bosman Street, Pretoria Central",
		driver: "Thabo Molefe",
		vehicle: "Toyota Hiace",
		licensePlate: "GP 789-012",
		fare: "R45.00",
		status: "completed",
		paymentMethod: "QR Code",
		rating: 4,
	},
	{
		id: "trip3",
		route: "Johannesburg CBD to Soweto",
		date: "2023-11-05",
		time: "17:45 PM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Old Potchefstroom Road, Soweto",
		driver: "Mandla Zulu",
		vehicle: "Nissan Impendulo",
		licensePlate: "GP 345-678",
		fare: "R20.00",
		status: "completed",
		paymentMethod: "Cash",
	},
	{
		id: "trip4",
		route: "Pretoria to Johannesburg",
		date: "2023-10-28",
		time: "09:00 AM",
		pickup: "Bosman Street, Pretoria Central",
		dropoff: "Bree Street, Johannesburg CBD",
		driver: "Themba Ndlovu",
		vehicle: "Toyota Quantum",
		licensePlate: "GP 901-234",
		fare: "R65.00",
		status: "cancelled",
		paymentMethod: "N/A",
	},
	{
		id: "trip5",
		route: "Johannesburg CBD to Sandton",
		date: "2023-10-20",
		time: "16:30 PM",
		pickup: "Bree Street, Johannesburg CBD",
		dropoff: "Rivonia Road, Sandton",
		driver: "David Mkhize",
		vehicle: "Mercedes-Benz Sprinter",
		licensePlate: "GP 567-890",
		fare: "R25.00",
		status: "completed",
		paymentMethod: "QR Code",
		rating: 5,
	},
];

// Additional dashboard data
export const drivers = [
	{
		id: "driver1",
		name: "Sipho Nkosi",
		phone: "073 123 4567",
		licenseNumber: "DL34567890",
		licenseExpiry: "2025-06-30",
		status: "active",
		joinDate: "2021-08-15",
		rating: 4.8,
		totalTrips: 1458,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver1",
		taxiId: "taxi1",
	},
	{
		id: "driver2",
		name: "Thabo Molefe",
		phone: "082 345 6789",
		licenseNumber: "DL12345678",
		licenseExpiry: "2024-10-15",
		status: "active",
		joinDate: "2020-03-22",
		rating: 4.5,
		totalTrips: 2105,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver2",
		taxiId: "taxi2",
	},
	{
		id: "driver3",
		name: "Mandla Zulu",
		phone: "076 567 8901",
		licenseNumber: "DL87654321",
		licenseExpiry: "2026-01-10",
		status: "active",
		joinDate: "2022-01-05",
		rating: 4.7,
		totalTrips: 873,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver3",
		taxiId: "taxi3",
	},
	{
		id: "driver4",
		name: "Themba Ndlovu",
		phone: "071 890 1234",
		licenseNumber: "DL76543210",
		licenseExpiry: "2023-11-20",
		status: "suspended",
		joinDate: "2019-11-30",
		rating: 3.9,
		totalTrips: 1267,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver4",
		taxiId: "taxi4",
	},
	{
		id: "driver5",
		name: "David Mkhize",
		phone: "084 012 3456",
		licenseNumber: "DL23456789",
		licenseExpiry: "2024-07-25",
		status: "active",
		joinDate: "2021-02-18",
		rating: 4.6,
		totalTrips: 982,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver5",
		taxiId: "taxi5",
	},
	{
		id: "driver6",
		name: "Bongani Dlamini",
		phone: "072 234 5678",
		licenseNumber: "DL98765432",
		licenseExpiry: "2025-03-14",
		status: "pending",
		joinDate: "2023-09-20",
		rating: 0,
		totalTrips: 0,
		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=driver6",
	},
];

// Taxi Documents
export const taxiDocuments = [
	{
		id: "doc1",
		taxiId: "taxi1",
		type: "vehicleRegistration",
		fileName: "GP_123-456_Registration.pdf",
		uploadDate: "2023-01-15",
		expiryDate: "2024-01-15",
		status: "verified",
	},
	{
		id: "doc2",
		taxiId: "taxi1",
		type: "insurance",
		fileName: "GP_123-456_Insurance.pdf",
		uploadDate: "2023-02-10",
		expiryDate: "2024-02-10",
		status: "verified",
	},
	{
		id: "doc3",
		taxiId: "taxi2",
		type: "vehicleRegistration",
		fileName: "GP_789-012_Registration.pdf",
		uploadDate: "2023-03-22",
		expiryDate: "2024-03-22",
		status: "verified",
	},
	{
		id: "doc4",
		taxiId: "taxi3",
		type: "vehicleRegistration",
		fileName: "GP_345-678_Registration.pdf",
		uploadDate: "2023-05-08",
		expiryDate: "2024-05-08",
		status: "pending",
	},
	{
		id: "doc5",
		taxiId: "taxi4",
		type: "insurance",
		fileName: "GP_901-234_Insurance.pdf",
		uploadDate: "2023-04-17",
		expiryDate: "2023-10-17",
		status: "expired",
	},
];

// Rank Details
export const rankDetails = ranks.map((rank) => ({
	...rank,
	capacity: Math.floor(Math.random() * 30) + 10,
	currentOccupancy: Math.floor(Math.random() * 20) + 5,
	operatingHours: "05:00 AM - 10:00 PM",
	facilities: ["Restrooms", "Waiting Area", "Food Vendors"].filter(() => Math.random() > 0.3),
	managers: ["John Smith", "Mary Johnson"].filter(() => Math.random() > 0.5),
	lastInspection: "2023-08-15",
}));

// Admin Users (definition removed, using the one with type at the bottom)
// export const adminUsers = [
// 	{
// 		id: "admin1",
// 		name: "Sarah Johnson",
// 		email: "sarah.johnson@taxiciti.co.za",
// 		role: "Super Admin",
// 		status: "active",
// 		lastLogin: "2023-11-20 09:45 AM",
// 		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=admin1",
// 	},
// 	{
// 		id: "admin2",
// 		name: "Michael Brown",
// 		email: "michael.brown@taxiciti.co.za",
// 		role: "Operations Manager",
// 		status: "active",
// 		lastLogin: "2023-11-19 16:30 PM",
// 		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=admin2",
// 	},
// 	{
// 		id: "admin3",
// 		name: "Thandi Nkosi",
// 		email: "thandi.nkosi@taxiciti.co.za",
// 		role: "Support Agent",
// 		status: "active",
// 		lastLogin: "2023-11-20 08:15 AM",
// 		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=admin3",
// 	},
// 	{
// 		id: "admin4",
// 		name: "David Wilson",
// 		email: "david.wilson@taxiciti.co.za",
// 		role: "Data Analyst",
// 		status: "inactive",
// 		lastLogin: "2023-11-15 14:20 PM",
// 		avatar: "https://img.heroui.chat/image/avatar?w=100&h=100&u=admin4",
// 	},
// ];

// Support Tickets
export const supportTickets = [
	{
		id: "ticket1",
		subject: "Payment not showing up",
		description: "Customer reported that payment was made but not showing in system",
		status: "open",
		priority: "high",
		createdDate: "2023-11-19 10:23 AM",
		customerName: "John Mbeki",
		customerEmail: "john.m@example.com",
		assignedTo: "admin3",
		category: "Payment",
	},
	{
		id: "ticket2",
		subject: "Driver behavior complaint",
		description: "Customer complained about rude behavior from driver",
		status: "in-progress",
		priority: "medium",
		createdDate: "2023-11-18 15:45 PM",
		customerName: "Lisa Smith",
		customerEmail: "lisa.smith@example.com",
		assignedTo: "admin3",
		category: "Driver Complaint",
		relatedDriverId: "driver2",
	},
	{
		id: "ticket3",
		subject: "App not showing available taxis",
		description: "User reported that no taxis are showing as available in the app",
		status: "open",
		priority: "high",
		createdDate: "2023-11-19 16:30 PM",
		customerName: "Peter Zulu",
		customerEmail: "p.zulu@example.com",
		assignedTo: null,
		category: "Technical Issue",
	},
	{
		id: "ticket4",
		subject: "Refund request for cancelled trip",
		description: "Customer requesting refund for trip that was cancelled by driver",
		status: "resolved",
		priority: "low",
		createdDate: "2023-11-17 09:15 AM",
		customerName: "Grace Moyo",
		customerEmail: "grace.m@example.com",
		assignedTo: "admin3",
		category: "Refund",
		resolution: "Refund processed on 2023-11-17",
	},
	{
		id: "ticket5",
		subject: "Lost item in taxi",
		description: "Customer left phone in taxi and needs help recovering it",
		status: "in-progress",
		priority: "medium",
		createdDate: "2023-11-18 13:40 PM",
		customerName: "Sam Ndlovu",
		customerEmail: "sam.n@example.com",
		assignedTo: "admin2",
		category: "Lost Item",
		relatedTripId: "trip2",
	},
];

// System Activity Logs
export const activityLogs = [
	{
		id: "log1",
		action: "User Login",
		description: "Admin user logged into system",
		timestamp: "2023-11-20 09:45:22",
		userId: "admin1",
		ipAddress: "196.25.102.45",
	},
	{
		id: "log2",
		action: "Driver Approved",
		description: "New driver application was approved",
		timestamp: "2023-11-20 10:15:36",
		userId: "admin2",
		ipAddress: "196.25.102.45",
		driverId: "driver6",
	},
	{
		id: "log3",
		action: "Route Added",
		description: "New route created in the system",
		timestamp: "2023-11-19 14:30:05",
		userId: "admin1",
		ipAddress: "196.25.102.45",
		routeId: "route5",
	},
	{
		id: "log4",
		action: "Taxi Suspended",
		description: "Taxi suspended due to maintenance issues",
		timestamp: "2023-11-19 16:22:18",
		userId: "admin2",
		ipAddress: "196.25.102.45",
		taxiId: "taxi5",
	},
	{
		id: "log5",
		action: "Report Generated",
		description: "Monthly revenue report was generated",
		timestamp: "2023-11-20 08:05:44",
		userId: "admin4",
		ipAddress: "196.25.102.45",
		reportType: "revenue",
	},
	{
		id: "log6",
		action: "Support Ticket Resolved",
		description: "Customer support ticket was marked as resolved",
		timestamp: "2023-11-18 11:45:30",
		userId: "admin3",
		ipAddress: "196.25.102.45",
		ticketId: "ticket4",
	},
];

// Report Templates
export const reportTemplates = [
	{
		id: "report1",
		name: "Daily Revenue Summary",
		description: "Daily summary of all revenue from trips",
		type: "revenue",
		format: "PDF",
		schedule: "daily",
		recipients: ["admin1@taxiciti.co.za", "admin2@taxiciti.co.za"],
	},
	{
		id: "report2",
		name: "Driver Performance",
		description: "Monthly analysis of driver ratings and trips",
		type: "performance",
		format: "Excel",
		schedule: "monthly",
		recipients: ["admin2@taxiciti.co.za"],
	},
	{
		id: "report3",
		name: "Rank Utilization",
		description: "Weekly analysis of rank capacity and usage",
		type: "operations",
		format: "PDF",
		schedule: "weekly",
		recipients: ["admin2@taxiciti.co.za", "admin4@taxiciti.co.za"],
	},
	{
		id: "report4",
		name: "Customer Satisfaction",
		description: "Quarterly report on customer ratings and feedback",
		type: "customer",
		format: "PDF",
		schedule: "quarterly",
		recipients: ["admin1@taxiciti.co.za", "admin3@taxiciti.co.za"],
	},
];

// Mock Admin Users Data
export const adminUsers: iAdminUser[] = [
	{
		id: "admin1",
		name: "Manelisi Mbola",
		email: "manelisi@taxiciti.co.za",
		role: "Super Admin",
		status: "active",
		lastLogin: "2023-11-15T08:30:00",
		avatar: "https://i.pravatar.cc/150?u=admin1",
	},
	{
		id: "admin2",
		name: "Sarah Johnson",
		email: "sarah@taxiciti.co.za",
		role: "Operations Manager",
		status: "active",
		lastLogin: "2023-11-14T14:20:00",
		avatar: "https://i.pravatar.cc/150?u=admin2",
	},
	{
		id: "admin3",
		name: "Thabo Nkosi",
		email: "thabo@taxiciti.co.za",
		role: "Support Agent",
		status: "active",
		lastLogin: "2023-11-15T09:15:00",
		avatar: "https://i.pravatar.cc/150?u=admin3",
	},
	{
		id: "admin4",
		name: "Lisa Wong",
		email: "lisa@taxiciti.co.za",
		role: "Data Analyst",
		status: "inactive",
		lastLogin: "2023-10-30T11:45:00",
		avatar: "https://i.pravatar.cc/150?u=admin4",
	},
];
